---
- name: configure AWS
  hosts: localhost
  gather_facts: false
  vars:
    - current_directory: "{{ lookup('env', 'PWD') }}"
  tasks:
    - name: Find policy.json by name
      find:
        paths: "{{ current_directory }}"
        patterns: "{{ policy_file }}"
        recurse: yes
      register: policy_file_matched_subdirectory

    - name: Matched policy file
      debug:
        msg: "Matched policy file: {{ policy_file_matched_subdirectory.files[0].path }}"

    - name: install awscli
      pip:
        name: awscli
        state: present

    - name: install boto
      pip:
        name: boto
        state: present

    - name: install boto3
      pip:
        name: boto3
        state: present

    - name: install botocore
      pip:
        name: botocore
        state: present

    - name: Create global AWS role
      iam_role:
        name: global-serverless-role-customphong391
        state: present
        assume_role_policy_document: "{{ lookup('file', lookup('fileglob', policy_file_matched_subdirectory.files[0].path)) }}"
        managed_policy:
          -  arn:aws:iam::aws:policy/AWSLambdaFullAccess
      register: iam_role_response

    - name: Set attributes
      set_stats:
        data:
          role_arn: "{{iam_role_response.arn}}"
