---
- hosts: all
  vars:
    - current_directory: "{{ lookup('env','PWD') }}"
  tasks:
    - name: Find swagger file by name
      find:
        paths: "{{ current_directory }}"
        patterns: "{{ swagger_file }}"
        recurse: yes
      register: matched_swagger_file

    - name: Check that the swagger.json exists
      stat:
        path: "{{ matched_swagger_file.files[0].path }}"
      register: swagger_spec

    - name: remove the old swagger specification
      file:
        path: "{{ matched_swagger_file.files[0].path }}"
        state: absent
      when: swagger_spec.stat.exists

    - name: Initialize empty swagger.json if it does not exist
      file:
        path: "{{ current_directory }}/{{ swagger_file }}"
        state: touch

    - name: Find generated swagger file by name
      find:
        paths: "{{ current_directory }}"
        patterns: "{{ swagger_file }}"
        recurse: yes
      register: matched_new_swagger_file

    - name: Set the basis for API
      copy:
        content: '{ "swagger": "2.0", "info": {"title": "{{ api_title }}", "description": "{{ api_description }}", "version": "{{ api_version }}" }, "paths": {}}'
        dest: "{{ matched_new_swagger_file.files[0].path }}"
