---
- name: Configure Azure
  hosts: localhost
  vars:
    location: westeurope
    resource_group: thumbnailgeneration-rg
    storage_account_name: storageaccforthanh
    sub_id: b988f1e0-3bed-4eae-bbc2-56e26230fd86
    container_name1: inputBucket
    container_name2: outputBucket
    myemail: truong1942@outlook.com
  tasks:
#NOTE: Azure Platform
    - name: install azure-cli
      pip:
        name: azure-cli
        state: present

    - name: Create resource group
      command: >
         az group create
         -l "{{ location }}"
         -n "{{ resource_group }}"
      register: resource_group_info

    - name: Create storage account
      command: >
         az storage account create
         --name "{{ storage_account_name }}"
         --resource-group "{{ resource_group }}"

#NOTE: Azure Blob Storages
    - name: List storage account keys
      command: >
         az storage account keys list
         -g "{{ resource_group }}"
         -n "{{ storage_account_name }}"
      register: storage_account_keys_list_output

    - set_fact:
        storage_keys: "{{ storage_account_keys_list_output.stdout|from_json }}"

    - debug: msg="{{ item.value['value'] }}"
      with_items: "{{ storage_keys }}"

#    - name: Az role assginment for creating blob storage
#      command: >
#         az role assignment create
#         --role "Storage Blob Data Contributor"
#         --assignee "{{ myemail }}"
#         --scope "/subscriptions/"{{ sub_id }}"/resourceGroups/"{{ resource_group }}"/providers/Microsoft.Storage/storageAccounts/"{{ storage_account_name }}"/blobServices/default/containers/"{{ container_name1 }}""

#    - name: Create storage container1
#      command: >
#         az storage container create
#         --account-name "{{ storage_account_name }}"
#         --name "{{ container_name1 }}"
#         --account-key "{{ storage_keys }}"
#         --auth-mode key

#    - name: Create storage container2
#      command: >
#         az storage container create
#         -n "{{ container_name2 }}"
