---
- name: Configure Azure
  hosts: localhost
  vars:
    resource_group: thumbnailgeneration-rg
    location: westeurope
    storage_account_name: storageaccforthanh
    current_directory: "{{ lookup('env', 'PWD') }}"
    function_app_name: myimageresizerappv01
    zip_file: X-test-ImageRes.zip
    app_serviceplan: ThumbnailFunctionPlan
    container_name1: inputBucket
    container_name2: outputBucket
  tasks:
#NOTE: Azure Platform
    - name: install azure-cli
      pip:
        name: azure-cli
        state: present

    - name: Create resource group
      command: >
         az group create
         -l "{{ location }}"
         -n "{{ resource_group }}"

    - name: Create storage account
      command: >
         az storage account create
         --name "{{ storage_account_name }}"
         --resource-group "{{ resource_group }}"

#NOTE: Azure Function
    - name: Find .zip file by name
      find:
        paths: "{{ current_directory }}"
        patterns: "{{ zip_file }}"
        recurse: yes
      register: zip_file_matched_subdirectory

    - name: Matched zip file
      debug:
        msg: "Matched zip file: {{ zip_file_matched_subdirectory.files[0].path }}"

    - name: Create appservice plan for Azure Function
      command: >
         az appservice plan create
         -g "{{ resource_group }}"
         -n "{{ app_serviceplan }}"

    - name: Create Azure Function
      command: >
         az functionapp create
         -g "{{ resource_group }}"
         -n "{{ function_app_name }}"
         -s "{{ storage_account_name }}"
         --functions-version 2
         --plan "{{ app_serviceplan }}"

    - name: Deploy code to Azure function
      command: >
         az functionapp deployment source config-zip
         -g "{{ resource_group }}"
         -n "{{ function_app_name }}"
         --src "{{ zip_file_matched_subdirectory.files[0].path }}"

#NOTE: Azure Blob Storages
#    - name: Create storage container1
#      command: >
#         az storage container create
#         -n "{{ container_name1 }}"
#         --auth-mode login

#    - name: Create storage container2
#      command: >
#         az storage container create
#         -n "{{ container_name2 }}"
