---
- name: Configure Azure
  hosts: localhost
  vars:
    location: westeurope
    resource_group: thumbnailgeneration-rg
    storage_account_name: storageaccforthanh
    container_name1: inputBucket
    container_name2: outputBucket
  tasks:
#NOTE: Azure Platform
    - name: install azure-cli
      pip:
        name: azure-cli
        state: present

    - name: Create resource group
      command: >
         az group create
         -l "{{ location }}"
         -n "{{ resource_group }}"
      register: resource_group_info

    - name: Create storage account
      command: >
         az storage account create
         --name "{{ storage_account_name }}"
         --resource-group "{{ resource_group }}"

#NOTE: Azure Blob Storages
    - debug:
        msg: "SubId: {{ resource_group_info.resourcegroups.id }}"

#    - name: Create storage container1
#      command: >
#         az storage container create
#         --account-name "{{ storage_account_name }}"
#         -n "{{ container_name1 }}"
#         --auth-mode login

#    - name: Create storage container2
#      command: >
#         az storage container create
#         -n "{{ container_name2 }}"
