# Note: Service Template for deploying ToDo List API Gateway Application
- hosts: localhost
  vars:
    - current_directory: "{{ lookup('env','PWD') }}"
    - region: eu-central-1
    - api_title: ToDo_List_API
    - api_description: API description for ToDo List API Application
    - api_version: "{{ lookup('pipe','date') }}"
  tasks:
    # Note: Setup & configuration of AWS Plattform
    - name: Install python module boto
      pip:
        name: boto
        state: latest

    - name: Install python module boto3
      pip:
        name: boto3
        state: latest

    - name: Install python module botocore
      pip:
        name: botocore
        state: latest

    - name: Install python module awscli
      pip:
        name: awscli
        state: latest

    - name: Create a role with description and tags
      iam_role:
        name: mynewrole
        state: present
        assume_role_policy_document: "{{ lookup('file','policy.json') }}"
        managed_policy:
          -  arn:aws:iam::aws:policy/AWSLambdaFullAccess
          -  arn:aws:iam::aws:policy/AmazonAPIGatewayInvokeFullAccess
      register: iam_role_response

    # Note: Setup & configuration of AWS API Gateway
    - name: Find swagger.yaml by name
      find:
        paths: "{{ current_directory }}"
        patterns: 'swagger.yaml,swagger.json'
        recurse: yes
      register: matched_swagger_file

    - debug:
        msg: "Founded swagger file: {{ matched_swagger_file.files[0].path }}"

    - name: Check that the swagger file exists
      stat:
        path: "{{ matched_swagger_file.files[0].path }}"
      register: swagger_spec

    - name: Remove the old swagger specification
      file:
        path: "{{ matched_swagger_file.files[0].path }}"
        state: absent
      when: swagger_spec.stat.exists

    - name: Set the basis for API
      copy:
        content: '{ "swagger": "2.0", "info": {"title": "{{ api_title }}", "description": "{{ api_description }}", "version": "{{ api_version }}" }, "paths": {"/todo": {}}}'
        dest: "{{ current_directory }}/swagger.json"

    - name: Setup AWS API Gateway setup on AWS and deploy API definition
      aws_api_gateway:
        state: present
        swagger_file: "{{ current_directory }}/swagger.json"
        stage: production
        region: "{{ region }}"
