---
- hosts: localhost
  vars:
    current_directory: "{{ lookup('env', 'PWD') }}"
    app_serviceplan: myserviceplan
    resource_group: serverlessresourcegroup
    storage_account: serverlessstorageac

#NOTE: Implement this vars into Node Types
    zip_file: list.zip
    region: westeurope
    api_title: myAPI
    pub_email: truong1942@outlook.com
    pub_name: api_phong
  tasks:
    - name: install azure-cli
      pip:
        name: azure-cli
        state: present

    - name: Create a resource group
      command: >
         az group create
         -l "{{ region }}"
         -n "{{ resource_group }}"

    - name: Create storage account
      command: >
         az storage account create
         --name "{{ storage_account }}"
         --resource-group "{{ resource_group }}"

    - name: Create api management service instance
      command: >
         az apim create
         --name "{{ api_title }}"
         -g "{{ resource_group }}"
         -l "{{ region }}"
         --publisher-email "{{ pub_email }}"
         --publisher-name "{{ pub_name }}"

    # - name: Find .zip file by name
    #   find:
    #     paths: "{{ current_directory }}"
    #     patterns: "{{ zip_file }}"
    #     recurse: yes
    #   register: zip_file_matched_subdirectory
    #
    # - name: Matched zip file
    #   debug:
    #     msg: "Matched zip file: {{ zip_file_matched_subdirectory.files[0].path }}"
    #
    # - name: Create appservice plan for Azure Function
    #   command: >
    #      az appservice plan create
    #      -g "{{ app_resource_group }}"
    #      -n "{{ app_serviceplan }}"
    #
    # - name: Create Azure Function
    #   command: >
    #      az functionapp create
    #      -g "{{ app_resource_group }}"
    #      -n "{{ function_name }}"
    #      -s "{{ app_storage_account }}"
    #      --functions-version 2
    #      --plan "{{ app_serviceplan }}"
    #
    # - name: Deploy code to Azure function
    #   command: >
    #      az functionapp deployment source config-zip
    #      -g "{{ app_resource_group }}"
    #      -n "{{ function_name }}"
    #      --src "{{ zip_file_matched_subdirectory.files[0].path }}"
