---
- hosts: localhost
  vars:
    - resource_group: serverlessresourcegroup
    - storage_account: serverlessstorageac
  tasks:
    - name: install azure-cli
      pip:
        name: azure-cli
        state: present

    - name: Create a resource group
      command: >
         az group create
         -l "{{ region }}"
         -n "{{ resource_group }}"

    - name: Create storage account
      command: >
         az storage account create
         --name "{{ storage_account }}"
         --resource-group "{{ resource_group }}"

    - name: Set attributes
      set_stats:
        data:
          app_resource_group: "{{ resource_group }}"
          app_storage_account: "{{ storage_account }}"
