---
- hosts: localhost
  tasks:
    - name: install azure-cli
      pip:
        name: azure-cli
        state: present

    - name: Create a resource group
      command: >
         az group create
         -l "{{ location }}"
         -n "{{ resource_group }}"

    - name: Create storage account
      command: >
         az storage account create
         --name "{{ storage_account_name }}"
         --resource-group "{{ resource_group }}"
