- name: Undeploy Azure Blob Storage
  hosts: localhost
  tasks:
    - name: Delete Azure Function
      command: >
         az functionapp delete
         -g "{{ app_resource_group }}"
         -n "{{ function_name }}"
