- name: Deploy Azure Blob Storage
  hosts: localhost
  vars:
    resource_group: storageblob-rg
    location: westus
    storage_account_name: clh0002
    deployment_user: thanni1234
    function_app_name: myimageresizerappv01
    current_directory: "{{ lookup('env', 'PWD') }}"
  tasks:
    - name: Delete a function app
      azure_rm_functionapp:
        resource_group: "{{ resource_group }}"
        name: "{{ function_app_name }}"
        state: absent
