- name: Deploy Azure Blob Storage
  hosts: localhost
  vars:
    resource_group: storageblob-rg
    location: westus
    storage_account_name: clh0002
    deployment_user: thanni1234
    function_app_name: myimageresizerappv01
    current_directory: "{{ lookup('env', 'PWD') }}"
  tasks:
    # NOTE: Shifted to configuration playbook
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Find .zip file by name
      find:
        paths: "{{ current_directory }}"
        patterns: "{{ zip_file }}"
        recurse: yes
      register: zip_file_matched_subdirectory

    - name: Matched zip file
      debug:
        msg: "Matched zip file: {{ zip_file_matched_subdirectory.files[0].path }}"

    - name: Create storage account
      azure_rm_storageaccount:
        resource_group: "{{ resource_group }}"
        name: "{{ storage_account_name }}"
        type: Standard_RAGRS

    - name: Create a function app
      azure_rm_functionapp:
        resource_group: "{{ resource_group }}"
        name: "{{ function_app_name }}"
        storage_account: "{{ storage_account_name }}"

    - name: Deploy code to Azure function
      command: >
         az functionapp deployment source config-zip
         -g "{{ resource_group }}"
         -n "{{ function_app_name }}"
         --src "{{ zip_file_matched_subdirectory }}"

    # NOTE: Needed if you want to push code to Azure function with REST API
    - name: Create deployment user account
      shell: 'curl -u "{{ deployment_user }}" https://"{{ function_app_name }}".scm.azurewebsites.net/api/deployments'
