---
- hosts: all
  tasks:
    - debug:
        msg: "This playbook was integrated in ../create/create.yml."

#    - name: Deploy API gateway
#      aws_api_gateway:
#        state: present
#        swagger_file: "/tmp/swagger.json"
#        stage: production
#        region: "{{ aws_region }}"
