---
- hosts: all
  tasks:
    - name: Find swagger file by name
      find:
        paths: "/tmp/"
        patterns: "{{ swagger_file }}"
        recurse: yes
      register: matched_swagger_file

    - name: Deploy API gateway
      aws_api_gateway:
        state: present
        swagger_file: "{{ matched_swagger_file.files[0].path }}"
        stage: production
        region: "{{ aws_region }}"
