---
- name: Configure Azure
  hosts: localhost
  vars:
    resource_group: thumbnailgeneration-rg
    location: westus
    storage_account_name: clh0002
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Create storage account
      azure_rm_storageaccount:
        resource_group: "{{ resource_group }}"
        name: "{{ storage_account_name }}"
        type: Standard_RAGRS
        
