---
- hosts: all
  tasks:
  - name: Configure gateway API swagger file
    template:
# Note: Temporary directory, need to change this later on
      src: "/home/phong/Desktop/API_deploy/APIGateway_w1-wip1/nodetypes/radon.nodes.aws/AwsApiGateway/files/RadonApiGateway.yaml"
      dest: "/home/phong/Desktop/API_deploy/APIGateway_w1-wip1/nodetypes/radon.nodes.aws/AwsApiGateway/files/RadonApiGatewayNew.yaml"
      mode: u=rw,g=r,o=r
    vars:
      api_gateway_resource_uri_override: "arn:aws:apigateway:{{ aws_region }}:lambda:path/2015-03-31/functions/{{ lambda_function_arn }}/invocations"

  - name: Deploy API gateway
    aws_api_gateway:
      state: present
      swagger_file: "/home/phong/Desktop/API_deploy/APIGateway_w1-wip1/nodetypes/radon.nodes.aws/AwsApiGateway/files/RadonApiGatewayNew.yaml"
      stage: production
      region: "{{ aws_region }}"
...