---
swagger: "2.0"
info:
  version: "2020-02-05T12:17:38Z"
  title: "{ get_property: [SELF, api_gateway_title] }"
host: "h8xiq5rvv8.execute-api.{ get_property: [SELF, aws_region] }.amazonaws.com"
basePath: "/production"
schemes:
  - "https"
paths:
  /:
    post:
      produces:
        - "application/json"
      responses:
        200:
          description: "200 response"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:{ get_property: [SELF, aws_region] }:lambda:path/2015-03-31/functions/{ get_attribute: [SELF, receives_notification, function_arn] }/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
        credentials: "{ get_attribute: [SELF, requires_role, role_arn] }"
    put:
      #TODO
    get:
      #TODO
    delete:
      #TODO
...