---
swagger: "2.0"
info:
  version: "2020-02-05T12:17:38Z"
  title: "Todo_List_API"
host: "h8xiq5rvv8.execute-api.us-east-1.amazonaws.com"
basePath: "/production"
schemes:
  - "https"
paths:
  /todo:
    post:
      tags:
        - "todo"
      summary: "Add a new todo note"
      description: ""
      operationId: "addTodo"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/json"
        - "application/xml"
      responses:
        "200":
          description: "Successful operation"
        "405":
          description: "Invalid input"
      x-amazon-apigateway-integration:
#>>REPLACE THIS URI LATER ON<<
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:557233580830:function:resize"
#>>REPLACE THIS URI LATER ON<<
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
        credentials: 'arn:aws:iam::557233580830:role/phong'
    put:
      tags:
        - "todo"
      summary: "Update an existing todo note"
      description: ""
      operationId: "updateTodo"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/json"
        - "application/xml"
      responses:
        "200":
          description: "Successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Todo note not found"
        "405":
          description: "Validation exception"
      x-amazon-apigateway-integration:
#>>REPLACE THIS URI LATER ON<<
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:557233580830:function:resize"
#>>REPLACE THIS URI LATER ON<<
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
        credentials: 'arn:aws:iam::557233580830:role/phong'
    get:
      tags:
        - "todo"
      summary: "Find pet by ID"
      description: "Returns a single todo note"
      operationId: "getTodoById"
      produces:
        - "application/json"
        - "application/xml"
      parameters:
      - name: "todoId"
        in: "path"
        description: "ID of todo to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Successful operation"
          # schema:
          #   $ref: "#/definitions/Pet"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      x-amazon-apigateway-integration:
#>>REPLACE THIS URI LATER ON<<
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:557233580830:function:resize"
#>>REPLACE THIS URI LATER ON<<
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
        credentials: 'arn:aws:iam::557233580830:role/phong'
    delete:
      tags:
        - "todo"
      summary: "Deletes a todo note"
      description: ""
      operationId: "deleteTodo"
      produces:
        - "application/json"
        - "application/xml"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "todoId"
        in: "path"
        description: "Todo id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Todo not found"
      x-amazon-apigateway-integration:
#>>REPLACE THIS URI LATER ON<<
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:557233580830:function:resize"
#>>REPLACE THIS URI LATER ON<<
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
        credentials: 'arn:aws:iam::557233580830:role/phong'
