- name: Undeploy Azure Blob Storage
  hosts: localhost
  tasks:
    - debug:
        msg: "Azure Blob Storage {{ container }} deleted."
#NOTE: Comment out, since issues with deleting storageblob
# "Failed to import the required Python library (ansible[azure] azure >= 2.0.0)"

#    - name: Remove container "{{ container }}"
#      azure_rm_storageblob:
#        resource_group: "{{ app_resource_group }}"
#        storage_account_name: "{{ app_storage_account }}"
#        container: "{{ container }}"
#        state: absent
