---
- hosts: localhost
  vars:
    - current_directory: "{{ lookup('env', 'PWD') }}"
  tasks:
    - name: Find policy.json by name
      find:
        paths: "{{ current_directory }}"
        patterns: 'policy.json'
        recurse: yes
      register: policy_file_matched_subdirectory

    - name: "Delete role of Lambda function on AWS : {{ function_name }}"
      iam_role:
        name: 'Lambda-role'
        assume_role_policy_document: "{{ lookup('file', lookup('fileglob', policy_file_matched_subdirectory.files[0].path)) }}"
        state: absent
