---
- name: Configure Azure
  hosts: localhost
  vars:
    resource_group: thumbnailgeneration-rg
    location: westeurope
    resource_group_name: newresourcegroupforthanh
    storage_account_name: newstorageaccountforthanh
  tasks:
    - name: install azure-cli
      pip:
        name: azure-cli
        state: present

    - name: Create a resource group
      command: >
         az group create
         -l "{{ location }}"
         -n "{{ resource_group }}"

    - name: Create storage account
      command: >
         az storage account create
         --name "{{ storage_account_name }}"
         --resource-group "{{ resource_group }}"
