---
- name: Configure Azure
  hosts: localhost
  vars:
    resource_group: thumbnailgeneration-rg
    location: germanywest
#    storage_account_name: clh0002
  tasks:
    - name: install azure-cli
      pip:
        name: azure-cli
        state: present

    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
