---
- name: Configure Azure
  hosts: localhost
  vars:
    resource_group: thumbnailgeneration-rg
    location: germanywest
    resource_group_name: newresourcegroupforthanh
    storage_account_name: newstorageaccountforthanh
  tasks:
    - name: install azure-cli
      pip:
        name: azure-cli
        state: present

    - name: Create a resource group
      command: >
         az group create
         -l "{{ resource_group_name }}"
         -n "{{ resource_group }}"

#    - name: Create storage account
#      azure_rm_storageaccount:
#        resource_group: "{{ resource_group_name }}"
#        name: "{{ storage_account_name }}"
#        type: Standard_RAGRS
#      register: azure_rm_storageaccount_response
