# Note: Service Template for deploying Thumbnail Generation Application
- hosts: localhost
  vars:
    APP_RESOURCE_GROUP: myResourceGroup
    APP_STORAGE_ACCOUNT: myStorageAccount
    REGION: germanywest
  tasks:
    # Note: Setup & configuration of Azure Plattform
    - name: install azure-cli
      pip:
        name: azure-cli
        state: present

    - name: install azure-functions
      pip:
        name: azure-functions
        state: present

    - name: install dotnet
      pip:
        name: dotnet
        state: present

    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ APP_RESOURCE_GROUP }}"
        location: "{{ REGION }}"

#    - name: Create storage account
#      azure_rm_storageaccount:
#        resource_group: "{{ APP_RESOURCE_GROUP }}"
#        name: "{{ APP_STORAGE_ACCOUNT }}"
#        type: Standard_RAGRS
