# Note: Service Template for deploying ToDo List API Gateway Application
- hosts: localhost
  tasks:
    # Note: Setup & configuration of AWS Plattform
    - name: Install python module boto
      pip:
        name: boto
        state: latest

    - name: Install python module boto3
      pip:
        name: boto3
        state: latest

    - name: Install python module botocore
      pip:
        name: botocore
        state: latest

    - name: Install python module awscli
      pip:
        name: awscli
        state: latest
