---
- name: configure AWS
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run simple generation script
      command: /usr/bin/python3 generator.py {{ matched_swagger_file.files[0].path }} {{ endpoint }} {{ http_methods }} {{ aws_region }} {{ function_arn }} {{ role_arn }}
