---
- name: configure AWS
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Find swagger file by name
      find:
        paths: "{{ current_directory }}"
        patterns: "{{ swagger_file }}"
        recurse: yes
      register: matched_swagger_file

    - name: Run simple generation script
      command: /usr/bin/python3 generator.py {{ matched_swagger_file.files[0].path }} {{ endpoint }} {{ http_methods }} {{ aws_region }} {{ function_arn }} {{ role_arn }}
