- name: Deploy Azure Blob Storage
  hosts: localhost
  tasks:
    - name: List storage account keys
      command: >
         az storage account keys list
         -g "{{ app_resource_group }}"
         -n "{{ app_storage_account }}"
      register: storage_account_keys_list_output

    - set_fact:
        storage_keys: "{{ storage_account_keys_list_output.stdout|from_json }}"

    - debug:
        msg: "Storage key value in first entry: {{ storage_keys[0].value }}"

    - name: Create storage container
      command: >
         az storage container create
         --account-name "{{ app_storage_account }}"
         --name "{{ container }}"
         --account-key "{{ storage_keys[0].value }}"
         --auth-mode key
