- name: Deploy Azure Function
  hosts: localhost
  vars:
    current_directory: "{{ lookup('env', 'PWD') }}"
    app_serviceplan: myserviceplan
  tasks:
    - name: Find .zip file by name
      find:
        paths: "{{ current_directory }}"
        patterns: "{{ zip_file }}"
        recurse: yes
      register: zip_file_matched_subdirectory

    - name: Matched zip file
      debug:
        msg: "Matched zip file: {{ zip_file_matched_subdirectory.files[0].path }}"

    - name: Create appservice plan for Azure Function
      command: >
         az appservice plan create
         -g "{{ app_resource_group }}"
         -n "{{ app_serviceplan }}"

    - name: Create Azure Function
      command: >
         az functionapp create
         -g "{{ app_resource_group }}"
         -n "{{ function_name }}"
         -s "{{ app_storage_account }}"
         --functions-version 2
         --plan "{{ app_serviceplan }}"

    - name: Deploy code to Azure function
      command: >
         az functionapp deployment source config-zip
         -g "{{ app_resource_group }}"
         -n "{{ function_name }}"
         --src "{{ zip_file_matched_subdirectory.files[0].path }}"
