- name: Deploy Azure Function
  hosts: localhost
  vars:
    current_directory: "{{ lookup('env', 'PWD') }}"
  tasks:
    - name: Find .zip file by name
      find:
        paths: "{{ current_directory }}"
        patterns: "{{ zip_file }}"
        recurse: yes
      register: zip_file_matched_subdirectory

    - name: Matched zip file
      debug:
        msg: "Matched zip file: {{ zip_file_matched_subdirectory.files[0].path }}"
#NOTE: Comment out, since issues with creating function app
# "Failed to import the required Python library (ansible[azure] azure >= 2.0.0)"

#    - name: Create a function app
#      azure_rm_functionapp:
#        resource_group: "{{ app_resource_group }}" #myResourceGroupforThumnailGen
#        name: "{{ function_name }}"
#        storage_account: "{{ app_storage_account }}" #mystorageaccount3194

#NOTE: replace this line below with line in task below for later deploy
#         -n "{{ function_name }}"
    - name: Deploy code to Azure function
      command: >
         az functionapp deployment source config-zip
         -g "{{ app_resource_group }}"
         -n mythumbnailfunctionapp
         --src "{{ zip_file_matched_subdirectory.files[0].path }}"
