---
- name: Delete resource group
  hosts: localhost
  vars:
    resource_group: thumbnailgeneration-rg
    location: westus
    storage_account_name: clh0002
  tasks:
    - name: Delete a resource group including resources it contains
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        force_delete_nonempty: yes
        state: absent
